server:
  port: 8080
spring:
  application:
    # 应用名称（当未配置下面那个服务名称时，Nacos会默认将该名称当做服务名称）
    name: order-service
  cloud:
    nacos:
      discovery:
        service: order-service  # 服务名称
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: f88a4197-4ae6-40c9-90cc-9c1a1146ed8c  # develop命名空间的id，不同命名空间的服务不能相互调用！
        group: order-group  # 指定服务的分组，默认为DEFAULT_GROUP，分组是对多个服务逻辑上的分类！
        ephemeral: false  # ephemeral意思为“短暂的”，默认为true，表示为临时实例（当服务器15s未收到心跳，则会将该服务的健康状态标记为false，超过30s则会直接删除该服务）
        # 为false则表示该服务为永久实例，即就算没有了心跳服务端也不会删除该服务！
        # 永久实例存在的一个意义是为了当某服务的"健康实例数/总实例数"<"保护阈值"时，触发的"雪崩保护"机制可以选择永久实例进行流量泄洪（即如果触发"雪崩保护"时流量突然变大，且该永久实例健康状态为false，则其依然可以接收客户端请求，并返回此服务不可用的信息，从而减缓了剩余健康实例的压力）
        weight: 1  # 通常要结合负载均衡一起使用，即权重高的服务优先被调用